import { StyleSheet } from 'react-native';
import { ThemeColors } from '../../constants/Colors';

export const createStyles = (
  colors: ThemeColors,
  isTablet: boolean,
  contentMaxWidth: number,
) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      maxWidth: contentMaxWidth,
      alignSelf: 'center',
      paddingHorizontal: isTablet ? 32 : 20,
      paddingTop: isTablet ? 16 : 12,
      paddingBottom: isTablet ? 12 : 8,
    },
    backButton: {
      width: isTablet ? 48 : 40,
      height: isTablet ? 48 : 40,
      borderRadius: 12,
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      color: colors.textEnabled,
      fontSize: isTablet ? 22 : 18,
      fontWeight: '700',
      marginLeft: isTablet ? 14 : 12,
      flexShrink: 1,
    },
    content: {
      flex: 1,
      width: '100%',
      maxWidth: contentMaxWidth,
      alignSelf: 'center',
      paddingHorizontal: isTablet ? 32 : 20,
      paddingTop: isTablet ? 20 : 16,
      paddingBottom: isTablet ? 32 : 24,
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      paddingBottom: isTablet ? 24 : 16,
      flexGrow: 1,
    },
    infoCard: {
      width: '100%',
      borderRadius: isTablet ? 20 : 16,
      borderWidth: 1.5,
      borderStyle: 'dashed',
      borderColor: colors.button,
      backgroundColor: colors.inputBox,
      paddingHorizontal: isTablet ? 20 : 16,
      paddingTop: isTablet ? 20 : 16,
      paddingBottom: isTablet ? 16 : 14,
    },
    titleRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
    },
    storeTitle: {
      flex: 1,
      color: colors.textEnabled,
      fontSize: isTablet ? 24 : 20,
      fontWeight: '700',
    },
    statusBadge: {
      borderRadius: 8,
      paddingHorizontal: isTablet ? 12 : 10,
      paddingVertical: isTablet ? 6 : 4,
      backgroundColor: colors.button + '33',
    },
    statusBadgeText: {
      color: colors.button,
      fontSize: isTablet ? 13 : 12,
      fontWeight: '700',
    },
    metaRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
      marginTop: isTablet ? 12 : 10,
    },
    metaText: {
      flex: 1,
      color: colors.textEnabled,
      fontSize: isTablet ? 15 : 14,
      fontWeight: '500',
      lineHeight: isTablet ? 22 : 20,
    },
    pauseReasonText: {
      color: colors.textDisabled,
      fontSize: isTablet ? 13 : 12,
      fontWeight: '500',
      marginTop: isTablet ? 10 : 8,
    },
    divider: {
      height: 1,
      backgroundColor: colors.border,
      marginTop: isTablet ? 16 : 14,
      marginBottom: isTablet ? 14 : 12,
      opacity: 0.8,
    },
    timeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    timeItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      flexShrink: 1,
    },
    timeText: {
      color: colors.textDisabled,
      fontSize: isTablet ? 13 : 12,
      fontWeight: '500',
    },
    actionsDivider: {
      height: 1,
      borderStyle: 'dashed',
      borderWidth: 1,
      borderColor: colors.button + '66',
      marginTop: isTablet ? 16 : 14,
      marginBottom: isTablet ? 14 : 12,
    },
    actionsRow: {
      flexDirection: 'row',
      gap: isTablet ? 14 : 12,
    },
    actionTile: {
      flex: 1,
      minHeight: isTablet ? 120 : 108,
      borderRadius: isTablet ? 16 : 14,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: isTablet ? 12 : 10,
      paddingVertical: isTablet ? 16 : 14,
    },
    actionIconBox: {
      width: isTablet ? 52 : 44,
      height: isTablet ? 52 : 44,
      borderRadius: isTablet ? 26 : 22,
      backgroundColor: colors.button + '1A',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: isTablet ? 12 : 10,
    },
    actionLabel: {
      color: colors.textEnabled,
      fontSize: isTablet ? 15 : 13,
      fontWeight: '700',
      textAlign: 'center',
    },
    actionStatus: {
      color: colors.textDisabled,
      fontSize: isTablet ? 12 : 11,
      fontWeight: '500',
      textAlign: 'center',
      marginTop: 4,
    },
    loadingWrap: {
      paddingVertical: isTablet ? 24 : 20,
      alignItems: 'center',
    },
    footer: {
      width: '100%',
      paddingTop: isTablet ? 12 : 8,
    },
    doneButton: {
      width: '100%',
      borderRadius: isTablet ? 16 : 14,
      overflow: 'hidden',
    },
    doneButtonDisabled: {
      opacity: 0.55,
    },
    doneGradient: {
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: isTablet ? 18 : 16,
      paddingHorizontal: isTablet ? 20 : 16,
      minHeight: isTablet ? 56 : 52,
    },
    doneText: {
      color: colors.buttonText,
      fontSize: isTablet ? 18 : 16,
      fontWeight: '700',
    },
    pauseLink: {
      marginTop: isTablet ? 12 : 10,
      alignSelf: 'stretch',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: '#E67E22',
      borderRadius: 10,
      paddingVertical: isTablet ? 12 : 10,
      paddingHorizontal: isTablet ? 16 : 12,
      backgroundColor: 'transparent',
    },
    pauseLinkText: {
      color: '#E67E22',
      fontSize: isTablet ? 15 : 14,
      fontWeight: '700',
    },
    pauseModalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.45)',
      justifyContent: 'center',
      paddingHorizontal: isTablet ? 40 : 24,
    },
    pauseModalCard: {
      backgroundColor: colors.background,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: isTablet ? 24 : 18,
    },
    pauseModalTitle: {
      color: colors.textEnabled,
      fontSize: isTablet ? 20 : 18,
      fontWeight: '700',
    },
    pauseModalSubtitle: {
      color: colors.textDisabled,
      fontSize: isTablet ? 14 : 13,
      marginTop: 6,
      marginBottom: 12,
    },
    pauseReasonRow: {
      paddingVertical: isTablet ? 12 : 10,
      paddingHorizontal: isTablet ? 14 : 12,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 8,
      backgroundColor: colors.inputBox,
    },
    pauseReasonRowSelected: {
      borderColor: colors.button,
    },
    pauseReasonText: {
      color: colors.textEnabled,
      fontSize: isTablet ? 15 : 14,
      fontWeight: '600',
    },
    pauseNoteInput: {
      minHeight: 80,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 10,
      padding: 12,
      color: colors.textEnabled,
      backgroundColor: colors.inputBox,
      textAlignVertical: 'top',
      marginBottom: 12,
    },
    pauseModalActions: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 8,
    },
    pauseModalSecondary: {
      flex: 1,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 12,
      alignItems: 'center',
    },
    pauseModalSecondaryText: {
      color: colors.textEnabled,
      fontWeight: '600',
    },
    pauseModalPrimary: {
      flex: 1,
      borderRadius: 10,
      backgroundColor: colors.button,
      paddingVertical: 12,
      alignItems: 'center',
    },
    pauseModalPrimaryText: {
      color: colors.buttonText,
      fontWeight: '700',
    },
  });
};
