import { StyleSheet } from 'react-native';
import { ThemeColors } from '../../constants/Colors';

export const createStyles = (
  colors: ThemeColors,
  isTablet: boolean,
  contentMaxWidth: number,
) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      paddingHorizontal: isTablet ? 32 : 20,
      paddingTop: isTablet ? 16 : 12,
      paddingBottom: isTablet ? 12 : 8,
      gap: 8,
      zIndex: 2,
      backgroundColor: colors.background,
    },
    backButton: {
      width: isTablet ? 48 : 40,
      height: isTablet ? 48 : 40,
      borderRadius: 12,
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      color: colors.textEnabled,
      fontSize: isTablet ? 22 : 18,
      fontWeight: '700',
    },
    checkOutButton: {
      paddingHorizontal: isTablet ? 22 : 18,
      paddingVertical: isTablet ? 12 : 10,
      borderRadius: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
    checkOutButtonDisabled: {
      opacity: 0.45,
    },
    checkOutText: {
      color: colors.buttonText,
      fontSize: isTablet ? 16 : 14,
      fontWeight: '700',
    },
    mapWrap: {
      flex: 1,
    },
    map: {
      flex: 1,
    },
    banner: {
      position: 'absolute',
      top: isTablet ? 12 : 8,
      left: isTablet ? 32 : 16,
      right: isTablet ? 32 : 16,
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: isTablet ? 16 : 12,
      paddingVertical: isTablet ? 12 : 10,
      zIndex: 3,
      alignItems: 'center',
    },
    bannerText: {
      color: colors.textEnabled,
      fontSize: isTablet ? 14 : 13,
      fontWeight: '500',
      textAlign: 'center',
    },
    bannerError: {
      color: '#FF4444',
    },
    retryText: {
      color: colors.button,
      fontSize: isTablet ? 14 : 13,
      fontWeight: '700',
      textAlign: 'center',
      marginTop: 8,
    },
    card: {
      position: 'absolute',
      left: isTablet ? 32 : 16,
      right: isTablet ? 32 : 16,
      maxWidth: isTablet ? contentMaxWidth : undefined,
      alignSelf: isTablet ? 'center' : undefined,
      backgroundColor: colors.inputBox,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: isTablet ? 20 : 16,
      paddingTop: isTablet ? 14 : 12,
      paddingBottom: isTablet ? 14 : 12,
      zIndex: 4,
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: isTablet ? 12 : 10,
    },
    cardHeaderMeta: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: isTablet ? 8 : 6,
      flexShrink: 0,
    },
    cardTitle: {
      flex: 1,
      color: colors.textEnabled,
      fontSize: isTablet ? 22 : 20,
      fontWeight: '700',
    },
    cardDistanceCompact: {
      color: colors.textDisabled,
      fontSize: isTablet ? 14 : 13,
      fontWeight: '600',
    },
    cardAddressRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 6,
      marginTop: isTablet ? 10 : 8,
    },
    cardAddress: {
      flex: 1,
      color: colors.textDisabled,
      fontSize: isTablet ? 14 : 13,
      fontWeight: '500',
      lineHeight: isTablet ? 20 : 18,
    },
    cardDistance: {
      color: colors.textDisabled,
      fontSize: isTablet ? 14 : 13,
      fontWeight: '500',
      marginTop: isTablet ? 8 : 6,
    },
    pauseReasonText: {
      color: colors.textDisabled,
      fontSize: isTablet ? 13 : 12,
      fontWeight: '500',
      marginTop: isTablet ? 8 : 6,
    },
    cardActions: {
      flexDirection: 'row',
      gap: isTablet ? 12 : 10,
      marginTop: isTablet ? 18 : 14,
    },
    startButton: {
      flex: 1,
      backgroundColor: '#FFFFFF',
      borderRadius: 10,
      paddingVertical: isTablet ? 14 : 12,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    startButtonDisabled: {
      opacity: 0.7,
    },
    startButtonText: {
      color: '#0B1422',
      fontSize: isTablet ? 15 : 14,
      fontWeight: '700',
    },
    detailsButton: {
      flex: 1,
      borderRadius: 10,
    },
    detailsGradient: {
      borderRadius: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingVertical: isTablet ? 14 : 12,
      paddingHorizontal: 12,
    },
    detailsButtonText: {
      color: colors.buttonText,
      fontSize: isTablet ? 15 : 14,
      fontWeight: '700',
    },
    secondaryActions: {
      flexDirection: 'row',
      gap: isTablet ? 12 : 10,
      marginTop: isTablet ? 12 : 10,
    },
    pauseLink: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: '#E67E22',
      borderRadius: 10,
      paddingVertical: isTablet ? 12 : 10,
      paddingHorizontal: isTablet ? 16 : 12,
      backgroundColor: 'transparent',
    },
    pauseLinkText: {
      color: '#E67E22',
      fontSize: isTablet ? 15 : 14,
      fontWeight: '700',
    },
    cancelLink: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: '#FF4444',
      borderRadius: 10,
      paddingVertical: isTablet ? 12 : 10,
      paddingHorizontal: isTablet ? 16 : 12,
      backgroundColor: 'transparent',
    },
    cancelLinkText: {
      color: '#FF4444',
      fontSize: isTablet ? 15 : 14,
      fontWeight: '700',
    },
    cancelModalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.45)',
      justifyContent: 'center',
      paddingHorizontal: isTablet ? 40 : 24,
    },
    cancelModalCard: {
      backgroundColor: colors.background,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: isTablet ? 24 : 18,
    },
    cancelModalTitle: {
      color: colors.textEnabled,
      fontSize: isTablet ? 20 : 18,
      fontWeight: '700',
    },
    cancelModalSubtitle: {
      color: colors.textDisabled,
      fontSize: isTablet ? 14 : 13,
      marginTop: 6,
      marginBottom: 12,
    },
    cancelReasonRow: {
      paddingVertical: isTablet ? 12 : 10,
      paddingHorizontal: isTablet ? 14 : 12,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 8,
      backgroundColor: colors.inputBox,
    },
    cancelReasonRowSelected: {
      borderColor: colors.button,
    },
    cancelReasonText: {
      color: colors.textEnabled,
      fontSize: isTablet ? 15 : 14,
      fontWeight: '600',
    },
    cancelNoteInput: {
      minHeight: 80,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 10,
      padding: 12,
      color: colors.textEnabled,
      backgroundColor: colors.inputBox,
      textAlignVertical: 'top',
      marginBottom: 12,
    },
    cancelModalActions: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 8,
    },
    cancelModalSecondary: {
      flex: 1,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 12,
      alignItems: 'center',
    },
    cancelModalSecondaryText: {
      color: colors.textEnabled,
      fontWeight: '600',
    },
    cancelModalPrimary: {
      flex: 1,
      borderRadius: 10,
      backgroundColor: colors.button,
      paddingVertical: 12,
      alignItems: 'center',
    },
    cancelModalPrimaryText: {
      color: colors.buttonText,
      fontWeight: '700',
    },
    chipScroll: {
      flexGrow: 0,
    },
    chipScrollContent: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingRight: 8,
    },
    chip: {
      paddingHorizontal: isTablet ? 14 : 12,
      paddingVertical: isTablet ? 10 : 8,
      borderRadius: 10,
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      minWidth: isTablet ? 120 : 104,
    },
    chipSelected: {
      borderColor: colors.button,
      backgroundColor: colors.inputBox,
    },
    chipText: {
      color: colors.textEnabled,
      fontSize: isTablet ? 13 : 12,
      fontWeight: '600',
    },
    chipTextSelected: {
      color: colors.button,
    },
    fabStack: {
      position: 'absolute',
      left: isTablet ? 16 : 10,
      top: isTablet ? 64 : 56,
      zIndex: 5,
      gap: isTablet ? 12 : 10,
    },
    fabRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      zIndex: 1,
    },
    fabRowOpen: {
      zIndex: 7,
      elevation: 7,
    },
    fabButton: {
      width: isTablet ? 52 : 45,
      height: isTablet ? 52 : 45,
      borderRadius: 12,
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    fabButtonActive: {
      borderColor: colors.button,
    },
    fabMenu: {
      position: 'absolute',
      left: '100%',
      top: 0,
      marginLeft: isTablet ? 10 : 8,
      zIndex: 6,
      flexDirection: 'column',
      alignItems: 'stretch',
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: isTablet ? 8 : 6,
      paddingVertical: isTablet ? 8 : 6,
      gap: 6,
    },
    mapLoader: {
      position: 'absolute',
      top: isTablet ? 12 : 8,
      left: isTablet ? 32 : 16,
      right: isTablet ? 32 : 16,
      zIndex: 6,
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: isTablet ? 16 : 12,
      paddingVertical: isTablet ? 12 : 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    mapBanner: {
      position: 'absolute',
      top: isTablet ? 12 : 8,
      left: isTablet ? 16 : 10,
      right: isTablet ? 16 : 10,
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: isTablet ? 16 : 12,
      paddingVertical: isTablet ? 12 : 10,
      zIndex: 6,
      alignItems: 'center',
    },
    mapBannerBelowLoader: {
      top: isTablet ? 64 : 56,
    },
    bannerWarning: {
      color: '#E67E22',
    },
    bannerInfo: {
      color: '#2563EB',
    },
    altRouteRow: {
      position: 'absolute',
      left: isTablet ? 32 : 16,
      right: isTablet ? 72 : 58,
      zIndex: 5,
    },
    altChip: {
      paddingHorizontal: isTablet ? 12 : 10,
      paddingVertical: isTablet ? 8 : 6,
      borderRadius: 999,
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      marginRight: 6,
    },
    altChipSelected: {
      borderColor: colors.button,
    },
    altChipText: {
      color: colors.textEnabled,
      fontSize: isTablet ? 12 : 11,
      fontWeight: '600',
    },
    altChipTextSelected: {
      color: colors.button,
    },
    progressTrack: {
      height: 4,
      borderRadius: 999,
      backgroundColor: colors.border,
      marginTop: isTablet ? 10 : 8,
      overflow: 'hidden',
    },
    progressFill: {
      height: 4,
      borderRadius: 999,
      backgroundColor: colors.button,
    },
  });
