export const ScreenNames = {
    SPLASH: 'Splash',
    FETCH_URL: 'FetchUrl',
    LOGIN: 'Login',
    HOME: 'Home',
    SETTINGS: 'Settings',
    PROFILE: 'Profile',
    CHECK_IN: 'CheckIn',
    SELFIE_CAMERA: 'SelfieCamera',
    GEO_MANAGEMENT: 'GeoManagement',
    GEO_HISTORY: 'GeoHistory',
    GEO_HISTORY_DAY: 'GeoHistoryDay',
    GEO_HISTORY_MAP: 'GeoHistoryMap',
    GEO_HISTORY_SESSION: 'GeoHistorySession',
    GEO_HISTORY_TASK_DETAIL: 'GeoHistoryTaskDetail',
    ATTENDANCE_CALENDAR: 'AttendanceCalendar',
    TIME_OFF_CALENDAR: 'TimeOffCalendar',
    TIME_OFF_REQUEST: 'TimeOffRequest',
    DEFAULT_ROUTE: 'DefaultRoute',
    TASK_ROUTING: 'TaskRouting',
    WHAT_NEEDS_TO_BE_DONE: 'WhatNeedsToBeDone',
    TASK_MAP: 'TaskMap',
    TASK_CAPTURE: 'TaskCapture',
    VIEW_DETAILS: 'ViewDetails',
} as const;
