import { StyleSheet } from 'react-native';
import { ThemeColors } from '../../constants/Colors';

export const createStyles = (
  colors: ThemeColors,
  isTablet: boolean,
  contentMaxWidth: number,
) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      maxWidth: contentMaxWidth,
      alignSelf: 'center',
      paddingHorizontal: isTablet ? 32 : 20,
      paddingTop: isTablet ? 16 : 12,
      paddingBottom: isTablet ? 12 : 8,
    },
    headerButton: {
      width: isTablet ? 48 : 40,
      height: isTablet ? 48 : 40,
      borderRadius: 12,
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      marginLeft: isTablet ? 12 : 10,
      color: colors.textEnabled,
      fontSize: isTablet ? 22 : 18,
      fontWeight: '700',
      textAlign: 'left',
    },
    keyboardView: {
      flex: 1,
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      width: '100%',
      maxWidth: contentMaxWidth,
      alignSelf: 'center',
      paddingHorizontal: isTablet ? 32 : 20,
      paddingTop: isTablet ? 16 : 12,
      paddingBottom: isTablet ? 28 : 20,
      gap: isTablet ? 14 : 12,
    },
    fieldRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: isTablet ? 16 : 14,
      minHeight: isTablet ? 56 : 52,
    },
    fieldRowError: {
      borderColor: '#FF4444',
    },
    fieldRowDisabled: {
      opacity: 0.85,
    },
    fieldText: {
      flex: 1,
      color: colors.textEnabled,
      fontSize: isTablet ? 17 : 16,
      paddingVertical: 14,
    },
    fieldPlaceholder: {
      color: colors.placeholder,
    },
    fieldIcon: {
      marginLeft: 8,
    },
    descriptionBox: {
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: isTablet ? 16 : 14,
      paddingVertical: isTablet ? 14 : 12,
      minHeight: isTablet ? 140 : 120,
    },
    descriptionInput: {
      color: colors.textEnabled,
      fontSize: isTablet ? 17 : 16,
      textAlignVertical: 'top',
      minHeight: isTablet ? 110 : 96,
      padding: 0,
    },
    attachmentRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: isTablet ? 8 : 4,
      gap: 12,
    },
    attachmentLabel: {
      flex: 1,
      color: colors.textEnabled,
      fontSize: isTablet ? 18 : 16,
      fontWeight: '700',
    },
    attachButton: {
      borderRadius: 10,
      overflow: 'hidden',
    },
    attachButtonGradient: {
      paddingHorizontal: isTablet ? 18 : 14,
      paddingVertical: isTablet ? 12 : 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    attachButtonText: {
      color: colors.buttonText,
      fontSize: isTablet ? 15 : 14,
      fontWeight: '700',
    },
    attachmentName: {
      color: colors.textDisabled,
      fontSize: isTablet ? 14 : 13,
      marginTop: 4,
    },
    previewBox: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      padding: isTablet ? 14 : 12,
      marginTop: isTablet ? 8 : 4,
      gap: 10,
    },
    previewContent: {
      flex: 1,
      gap: isTablet ? 10 : 8,
    },
    previewThumbnail: {
      width: '100%',
      height: isTablet ? 180 : 160,
      borderRadius: 8,
      backgroundColor: colors.border,
    },
    pdfPreviewRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: isTablet ? 14 : 12,
      minHeight: isTablet ? 64 : 56,
    },
    pdfPreviewTextWrap: {
      flex: 1,
      gap: 2,
    },
    previewFileName: {
      color: colors.textEnabled,
      fontSize: isTablet ? 15 : 14,
      fontWeight: '600',
    },
    previewHint: {
      color: colors.textDisabled,
      fontSize: isTablet ? 13 : 12,
    },
    previewRemoveButton: {
      width: isTablet ? 36 : 32,
      height: isTablet ? 36 : 32,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
    },
    imagePreviewOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.92)',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: isTablet ? 24 : 16,
      paddingVertical: isTablet ? 48 : 40,
    },
    imagePreviewClose: {
      position: 'absolute',
      top: isTablet ? 48 : 40,
      right: isTablet ? 28 : 20,
      zIndex: 2,
      width: isTablet ? 44 : 40,
      height: isTablet ? 44 : 40,
      borderRadius: 22,
      backgroundColor: 'rgba(255,255,255,0.18)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    imagePreviewFull: {
      width: '100%',
      height: '100%',
    },
    footer: {
      flexDirection: 'row',
      width: '100%',
      maxWidth: contentMaxWidth,
      alignSelf: 'center',
      paddingHorizontal: isTablet ? 32 : 20,
      paddingTop: isTablet ? 12 : 10,
      gap: isTablet ? 14 : 12,
    },
    discardButton: {
      flex: 1,
      borderRadius: 10,
      borderWidth: 1.5,
      borderColor: colors.button,
      backgroundColor: colors.inputBox,
      paddingVertical: isTablet ? 16 : 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    discardText: {
      color: colors.textEnabled,
      fontSize: isTablet ? 16 : 15,
      fontWeight: '700',
    },
    submitButton: {
      flex: 1,
      borderRadius: 10,
    },
    submitGradient: {
      borderRadius: 10,
      paddingVertical: isTablet ? 16 : 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    submitText: {
      color: colors.buttonText,
      fontSize: isTablet ? 16 : 15,
      fontWeight: '700',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'flex-end',
    },
    modalSheet: {
      backgroundColor: colors.background,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: isTablet ? 24 : 20,
      paddingTop: isTablet ? 20 : 16,
      maxHeight: '70%',
    },
    modalTitle: {
      color: colors.textEnabled,
      fontSize: isTablet ? 20 : 18,
      fontWeight: '700',
      marginBottom: isTablet ? 16 : 12,
    },
    optionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: isTablet ? 16 : 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    optionText: {
      color: colors.textEnabled,
      fontSize: isTablet ? 17 : 16,
      fontWeight: '500',
    },
    optionTextSelected: {
      color: colors.button,
      fontWeight: '700',
    },
    dateModalSheet: {
      backgroundColor: colors.background,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: isTablet ? 24 : 20,
      paddingTop: isTablet ? 20 : 16,
      paddingBottom: isTablet ? 16 : 12,
    },
    dateModalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: isTablet ? 16 : 12,
    },
    dateModalTitle: {
      color: colors.textEnabled,
      fontSize: isTablet ? 20 : 18,
      fontWeight: '700',
    },
    monthNav: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    monthNavButton: {
      width: isTablet ? 36 : 32,
      height: isTablet ? 36 : 32,
      alignItems: 'center',
      justifyContent: 'center',
    },
    monthNavButtonDisabled: {
      opacity: 0.4,
    },
    weekdayRow: {
      flexDirection: 'row',
      marginBottom: isTablet ? 10 : 8,
    },
    weekdayCell: {
      flex: 1,
      alignItems: 'center',
    },
    weekdayText: {
      color: colors.textDisabled,
      fontSize: isTablet ? 13 : 11,
      fontWeight: '600',
    },
    daysGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    dayCell: {
      width: '14.2857%',
      alignItems: 'center',
      paddingVertical: isTablet ? 6 : 4,
    },
    dayNumberWrap: {
      width: isTablet ? 36 : 32,
      height: isTablet ? 36 : 32,
      borderRadius: isTablet ? 18 : 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dayNumberWrapSelected: {
      backgroundColor: colors.button,
    },
    dayNumber: {
      color: colors.textEnabled,
      fontSize: isTablet ? 14 : 13,
      fontWeight: '600',
    },
    dayNumberOutside: {
      color: colors.textDisabled,
    },
    dayNumberDisabled: {
      color: colors.placeholder,
      opacity: 0.45,
    },
    dayNumberSelected: {
      color: colors.buttonText,
    },
  });
