import { StyleSheet } from 'react-native';
import { ThemeColors } from '../../constants/Colors';

export const createStyles = (
  colors: ThemeColors,
  isTablet: boolean,
  contentMaxWidth: number,
) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      maxWidth: contentMaxWidth,
      alignSelf: 'center',
      paddingHorizontal: isTablet ? 32 : 20,
      paddingTop: isTablet ? 16 : 12,
      paddingBottom: isTablet ? 12 : 8,
      gap: 8,
    },
    backButton: {
      width: isTablet ? 48 : 40,
      height: isTablet ? 48 : 40,
      borderRadius: 12,
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      color: colors.textEnabled,
      fontSize: isTablet ? 22 : 18,
      fontWeight: '700',
    },
    headerButton: {
      width: isTablet ? 48 : 40,
      height: isTablet ? 48 : 40,
      borderRadius: 12,
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerActions: {
      marginLeft: 'auto',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    listContent: {
      width: '100%',
      maxWidth: contentMaxWidth,
      alignSelf: 'center',
      paddingHorizontal: isTablet ? 32 : 20,
      paddingTop: isTablet ? 12 : 8,
      gap: isTablet ? 14 : 12,
    },
    filtersHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: isTablet ? 12 : 10,
    },
    dateFilterRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: isTablet ? 16 : 14,
      paddingVertical: isTablet ? 14 : 12,
      marginBottom: isTablet ? 14 : 12,
      gap: 12,
    },
    dateFilterTextWrap: {
      flex: 1,
      gap: 2,
    },
    dateFilterLabel: {
      color: colors.textDisabled,
      fontSize: isTablet ? 12 : 11,
      fontWeight: '600',
      letterSpacing: 0.4,
      textTransform: 'uppercase',
    },
    dateFilterValue: {
      color: colors.textEnabled,
      fontSize: isTablet ? 16 : 15,
      fontWeight: '700',
    },
    filtersLabel: {
      color: colors.textEnabled,
      fontSize: isTablet ? 13 : 12,
      fontWeight: '700',
      letterSpacing: 0.8,
    },
    clearAll: {
      color: colors.button,
      fontSize: isTablet ? 14 : 13,
      fontWeight: '600',
    },
    chipRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: isTablet ? 10 : 8,
      marginBottom: isTablet ? 8 : 4,
    },
    chip: {
      borderRadius: 20,
      overflow: 'hidden',
    },
    chipInner: {
      paddingHorizontal: isTablet ? 18 : 14,
      paddingVertical: isTablet ? 10 : 8,
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 20,
    },
    chipInnerSelected: {
      borderWidth: 0,
    },
    chipText: {
      color: colors.textDisabled,
      fontSize: isTablet ? 14 : 13,
      fontWeight: '600',
    },
    chipTextSelected: {
      color: colors.buttonText,
    },
    checkInBanner: {
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: isTablet ? 16 : 12,
      paddingVertical: isTablet ? 12 : 10,
      marginBottom: isTablet ? 12 : 10,
    },
    checkInBannerText: {
      color: '#FF4444',
      fontSize: isTablet ? 14 : 13,
      fontWeight: '600',
      textAlign: 'center',
    },
    resumeBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.button,
      borderRadius: 12,
      paddingHorizontal: isTablet ? 16 : 12,
      paddingVertical: isTablet ? 14 : 12,
      marginBottom: isTablet ? 12 : 10,
      gap: 8,
    },
    resumeBannerText: {
      flex: 1,
      color: colors.textEnabled,
      fontSize: isTablet ? 15 : 14,
      fontWeight: '600',
    },
    card: {
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 16,
      paddingHorizontal: isTablet ? 18 : 16,
      paddingTop: isTablet ? 16 : 14,
      paddingBottom: isTablet ? 14 : 12,
    },
    cardTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
    },
    cardTitle: {
      flex: 1,
      color: colors.textEnabled,
      fontSize: isTablet ? 18 : 16,
      fontWeight: '700',
    },
    badgeRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'flex-end',
      gap: 6,
      maxWidth: '52%',
    },
    statusBadge: {
      borderRadius: 8,
      paddingHorizontal: isTablet ? 10 : 8,
      paddingVertical: isTablet ? 5 : 4,
    },
    statusBadgePending: {
      backgroundColor: '#FDF2D7',
    },
    statusBadgeActive: {
      backgroundColor: '#E0E7FF',
    },
    statusBadgePaused: {
      backgroundColor: '#FFEDD5',
    },
    statusBadgeCompleted: {
      backgroundColor: '#DCFCE7',
    },
    statusBadgeOverdue: {
      backgroundColor: '#FEE2E2',
    },
    statusBadgeUpcoming: {
      backgroundColor: '#DBEAFE',
    },
    statusBadgeText: {
      fontSize: isTablet ? 12 : 11,
      fontWeight: '700',
    },
    statusBadgeTextPending: {
      color: '#B45D06',
    },
    statusBadgeTextActive: {
      color: '#3730A3',
    },
    statusBadgeTextPaused: {
      color: '#C2410C',
    },
    statusBadgeTextCompleted: {
      color: '#166534',
    },
    statusBadgeTextOverdue: {
      color: '#B91C1C',
    },
    statusBadgeTextUpcoming: {
      color: '#1D4ED8',
    },
    addressRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 6,
      marginTop: isTablet ? 10 : 8,
    },
    addressText: {
      flex: 1,
      color: colors.textEnabled,
      fontSize: isTablet ? 14 : 13,
      fontWeight: '500',
      lineHeight: isTablet ? 20 : 18,
    },
    dateRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginTop: isTablet ? 8 : 6,
    },
    dateRangeText: {
      flex: 1,
      color: colors.textDisabled,
      fontSize: isTablet ? 14 : 13,
      fontWeight: '500',
    },
    actionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: isTablet ? 16 : 14,
      gap: isTablet ? 14 : 12,
    },
    ctaButton: {
      borderRadius: 10,
      overflow: 'hidden',
    },
    ctaButtonDisabled: {
      opacity: 0.55,
    },
    ctaGradient: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: isTablet ? 18 : 14,
      paddingVertical: isTablet ? 12 : 10,
      gap: 6,
    },
    ctaText: {
      color: colors.buttonText,
      fontSize: isTablet ? 15 : 14,
      fontWeight: '700',
    },
    distanceText: {
      flex: 1,
      color: colors.textDisabled,
      fontSize: isTablet ? 14 : 13,
      fontWeight: '500',
    },
    cardDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.border,
      marginTop: isTablet ? 14 : 12,
      marginBottom: isTablet ? 10 : 8,
    },
    footerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 2,
    },
    footerText: {
      flex: 1,
      color: colors.textEnabled,
      fontSize: isTablet ? 15 : 14,
      fontWeight: '600',
    },
    emptyState: {
      alignItems: 'center',
      paddingVertical: isTablet ? 48 : 40,
    },
    emptyText: {
      color: colors.textDisabled,
      fontSize: isTablet ? 16 : 14,
      fontWeight: '500',
      textAlign: 'center',
    },
    paginationRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: isTablet ? 16 : 12,
      marginBottom: isTablet ? 8 : 4,
      gap: 8,
    },
    paginationButton: {
      minWidth: isTablet ? 96 : 84,
      paddingHorizontal: isTablet ? 14 : 12,
      paddingVertical: isTablet ? 12 : 10,
      borderRadius: 10,
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
    },
    paginationButtonDisabled: {
      opacity: 0.45,
    },
    paginationButtonText: {
      color: colors.button,
      fontSize: isTablet ? 14 : 13,
      fontWeight: '700',
    },
    paginationButtonTextDisabled: {
      color: colors.textDisabled,
    },
    paginationInfo: {
      flex: 1,
      textAlign: 'center',
      color: colors.textEnabled,
      fontSize: isTablet ? 14 : 13,
      fontWeight: '600',
    },
    errorText: {
      color: '#FF4444',
      fontSize: isTablet ? 14 : 13,
      fontWeight: '500',
      textAlign: 'center',
      paddingVertical: isTablet ? 16 : 12,
    },
    loadingWrap: {
      paddingVertical: isTablet ? 40 : 32,
      alignItems: 'center',
    },
  });
