import { StyleSheet } from 'react-native';
import { ThemeColors } from '../../constants/Colors';

export const createStyles = (
  colors: ThemeColors,
  isTablet: boolean,
  contentMaxWidth: number,
) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      maxWidth: contentMaxWidth,
      alignSelf: 'center',
      paddingHorizontal: isTablet ? 32 : 20,
      paddingTop: isTablet ? 16 : 12,
      paddingBottom: isTablet ? 12 : 8,
    },
    backButton: {
      width: isTablet ? 48 : 40,
      height: isTablet ? 48 : 40,
      borderRadius: 12,
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      color: colors.textEnabled,
      fontSize: isTablet ? 22 : 18,
      fontWeight: '700',
      marginLeft: isTablet ? 14 : 12,
      flexShrink: 1,
    },
    content: {
      flex: 1,
      width: '100%',
      maxWidth: contentMaxWidth,
      alignSelf: 'center',
      paddingHorizontal: isTablet ? 32 : 20,
      paddingTop: isTablet ? 28 : 20,
      paddingBottom: isTablet ? 32 : 24,
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      paddingBottom: isTablet ? 24 : 16,
      flexGrow: 1,
    },
    grid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      gap: isTablet ? 20 : 14,
    },
    card: {
      width: '48%',
      aspectRatio: 1.05,
      borderRadius: isTablet ? 20 : 16,
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: isTablet ? 16 : 12,
      paddingVertical: isTablet ? 20 : 16,
    },
    iconBox: {
      width: isTablet ? 56 : 44,
      height: isTablet ? 56 : 44,
      borderRadius: isTablet ? 14 : 12,
      backgroundColor: colors.button + '1A',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: isTablet ? 16 : 12,
    },
    cardLabel: {
      color: colors.textEnabled,
      fontSize: isTablet ? 16 : 14,
      fontWeight: '600',
      textAlign: 'center',
    },
    cardStatus: {
      color: colors.textDisabled,
      fontSize: isTablet ? 13 : 11,
      fontWeight: '500',
      textAlign: 'center',
      marginTop: isTablet ? 8 : 6,
    },
    previewSection: {
      marginTop: isTablet ? 28 : 20,
      width: '100%',
    },
    previewTitle: {
      color: colors.textEnabled,
      fontSize: isTablet ? 18 : 16,
      fontWeight: '700',
      marginBottom: isTablet ? 12 : 10,
    },
    previewPanel: {
      width: '100%',
      borderRadius: isTablet ? 20 : 16,
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: isTablet ? 20 : 16,
      paddingVertical: isTablet ? 20 : 16,
    },
    previewBlock: {
      width: '100%',
    },
    previewBlockSpaced: {
      marginTop: isTablet ? 20 : 16,
    },
    previewBlockLabel: {
      color: colors.textDisabled,
      fontSize: isTablet ? 13 : 12,
      fontWeight: '600',
      marginBottom: isTablet ? 10 : 8,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    noteBox: {
      width: '100%',
      borderRadius: isTablet ? 14 : 12,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: isTablet ? 16 : 14,
      paddingVertical: isTablet ? 14 : 12,
      minHeight: isTablet ? 96 : 80,
    },
    noteText: {
      color: colors.textEnabled,
      fontSize: isTablet ? 16 : 14,
      fontWeight: '400',
      lineHeight: isTablet ? 24 : 21,
    },
    selfieWrap: {
      width: isTablet ? 200 : 160,
      height: isTablet ? 200 : 160,
      borderRadius: isTablet ? 16 : 14,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.background,
    },
    selfieImage: {
      width: '100%',
      height: '100%',
    },
    footer: {
      width: '100%',
      paddingTop: isTablet ? 12 : 8,
    },
    doneButton: {
      width: '100%',
      borderRadius: isTablet ? 16 : 14,
      overflow: 'hidden',
    },
    doneButtonDisabled: {
      opacity: 0.7,
    },
    doneGradient: {
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: isTablet ? 18 : 16,
      paddingHorizontal: isTablet ? 20 : 16,
      minHeight: isTablet ? 56 : 52,
    },
    doneText: {
      color: colors.buttonText,
      fontSize: isTablet ? 18 : 16,
      fontWeight: '700',
    },
  });
};
