import { StyleSheet } from 'react-native';
import { ThemeColors } from '../../constants/Colors';

export const createStyles = (
  colors: ThemeColors,
  isTablet: boolean,
  contentMaxWidth: number,
) => {
  const checkInButtonSize = isTablet ? 200 : 168;

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      maxWidth: contentMaxWidth,
      alignSelf: 'center',
      paddingHorizontal: isTablet ? 32 : 20,
      paddingTop: isTablet ? 16 : 12,
      paddingBottom: isTablet ? 12 : 8,
    },
    backButton: {
      width: isTablet ? 48 : 40,
      height: isTablet ? 48 : 40,
      borderRadius: 12,
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 1,
    },
    headerTitle: {
      position: 'absolute',
      left: 0,
      right: 0,
      textAlign: 'center',
      color: colors.textEnabled,
      fontSize: isTablet ? 22 : 18,
      fontWeight: '700',
    },
    content: {
      flex: 1,
      width: '100%',
      maxWidth: contentMaxWidth,
      alignSelf: 'center',
      paddingHorizontal: isTablet ? 32 : 20,
      paddingTop: isTablet ? 28 : 20,
      paddingBottom: isTablet ? 32 : 24,
      justifyContent: 'space-between',
    },
    topSection: {
      alignItems: 'center',
    },
    greeting: {
      color: colors.textEnabled,
      fontSize: isTablet ? 32 : 28,
      fontWeight: '700',
      textAlign: 'center',
    },
    jobTitle: {
      color: colors.textDisabled,
      fontSize: isTablet ? 17 : 15,
      fontWeight: '500',
      textAlign: 'center',
      marginTop: 6,
    },
    time: {
      color: colors.textEnabled,
      fontSize: isTablet ? 64 : 52,
      fontWeight: '700',
      textAlign: 'center',
      marginTop: isTablet ? 36 : 28,
      letterSpacing: 1,
    },
    date: {
      color: colors.textDisabled,
      fontSize: isTablet ? 18 : 16,
      fontWeight: '500',
      textAlign: 'center',
      marginTop: 8,
    },
    middleSection: {
      alignItems: 'center',
    },
    checkInWrap: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    checkInButton: {
      width: checkInButtonSize,
      height: checkInButtonSize,
      borderRadius: checkInButtonSize / 2,
      overflow: 'hidden',
      shadowColor: colors.button,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.35,
      shadowRadius: 20,
      elevation: 10,
    },
    checkInGradient: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: checkInButtonSize / 2,
    },
    checkInLabel: {
      color: colors.buttonText,
      fontSize: isTablet ? 22 : 20,
      fontWeight: '700',
      marginTop: 10,
    },
    selfieChip: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: isTablet ? 20 : 16,
      paddingVertical: isTablet ? 10 : 8,
      paddingHorizontal: isTablet ? 14 : 12,
      borderRadius: 12,
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      gap: isTablet ? 12 : 10,
    },
    selfieThumb: {
      width: isTablet ? 48 : 40,
      height: isTablet ? 48 : 40,
      borderRadius: isTablet ? 24 : 20,
      backgroundColor: colors.border,
    },
    selfieLabel: {
      color: colors.textEnabled,
      fontSize: isTablet ? 15 : 13,
      fontWeight: '600',
    },
    distanceText: {
      color: colors.textDisabled,
      fontSize: isTablet ? 15 : 13,
      fontWeight: '500',
      textAlign: 'center',
      marginTop: isTablet ? 28 : 24,
    },
    placeText: {
      color: colors.textEnabled,
      fontSize: isTablet ? 16 : 14,
      fontWeight: '700',
      textAlign: 'center',
      marginTop: 4,
    },
    summaryCard: {
      flexDirection: 'row',
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 16,
      paddingVertical: isTablet ? 22 : 18,
      paddingHorizontal: isTablet ? 12 : 8,
    },
    summaryItem: {
      flex: 1,
      alignItems: 'center',
    },
    summaryValue: {
      color: colors.textEnabled,
      fontSize: isTablet ? 18 : 16,
      fontWeight: '700',
      marginTop: 10,
    },
    summaryLabel: {
      color: colors.textEnabled,
      fontSize: isTablet ? 13 : 12,
      fontWeight: '500',
      marginTop: 4,
    },
  });
};
