import { StyleSheet } from 'react-native';
import { ThemeColors } from '../../constants/Colors';

export const createStyles = (
  colors: ThemeColors,
  isTablet: boolean,
  contentMaxWidth: number,
) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      maxWidth: contentMaxWidth,
      alignSelf: 'center',
      paddingHorizontal: isTablet ? 32 : 20,
      paddingTop: isTablet ? 16 : 12,
      paddingBottom: isTablet ? 12 : 8,
      gap: 8,
    },
    backButton: {
      width: isTablet ? 48 : 40,
      height: isTablet ? 48 : 40,
      borderRadius: 12,
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      color: colors.textEnabled,
      fontSize: isTablet ? 22 : 18,
      fontWeight: '700',
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      width: '100%',
      maxWidth: contentMaxWidth,
      alignSelf: 'center',
      paddingHorizontal: isTablet ? 32 : 20,
      paddingTop: isTablet ? 12 : 8,
      gap: isTablet ? 12 : 10,
    },
    sectionTitle: {
      color: colors.textEnabled,
      fontSize: isTablet ? 20 : 18,
      fontWeight: '700',
      marginTop: isTablet ? 12 : 10,
      marginBottom: isTablet ? 4 : 2,
    },
    itemCard: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: isTablet ? 12 : 10,
      backgroundColor: colors.inputBox,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: isTablet ? 18 : 16,
      paddingVertical: isTablet ? 16 : 14,
    },
    itemCardDone: {
      borderColor: colors.button,
    },
    itemTextWrap: {
      flex: 1,
    },
    itemText: {
      color: colors.textEnabled,
      fontSize: isTablet ? 16 : 15,
      fontWeight: '500',
      lineHeight: isTablet ? 24 : 22,
    },
    requiredTag: {
      marginTop: 4,
      color: colors.textDisabled,
      fontSize: isTablet ? 12 : 11,
      fontWeight: '600',
    },
    hintText: {
      color: colors.textDisabled,
      fontSize: isTablet ? 13 : 12,
      fontWeight: '500',
      marginBottom: isTablet ? 10 : 8,
      lineHeight: isTablet ? 20 : 18,
    },
    selectAllRow: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      alignItems: 'center',
      marginTop: isTablet ? 4 : 2,
      marginBottom: isTablet ? 2 : 0,
    },
    selectAllText: {
      color: colors.button,
      fontSize: isTablet ? 15 : 14,
      fontWeight: '700',
      paddingVertical: isTablet ? 6 : 4,
      paddingHorizontal: isTablet ? 4 : 2,
    },
    footer: {
      width: '100%',
      maxWidth: contentMaxWidth,
      alignSelf: 'center',
      paddingHorizontal: isTablet ? 32 : 20,
      paddingTop: isTablet ? 12 : 10,
    },
    startButton: {
      borderRadius: 12,
      overflow: 'hidden',
    },
    startGradient: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: isTablet ? 18 : 16,
      paddingHorizontal: isTablet ? 24 : 20,
    },
    startText: {
      color: colors.buttonText,
      fontSize: isTablet ? 17 : 16,
      fontWeight: '700',
    },
    loadingWrap: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: isTablet ? 40 : 32,
    },
    errorText: {
      color: '#FF4444',
      fontSize: isTablet ? 14 : 13,
      fontWeight: '500',
      textAlign: 'center',
      paddingVertical: isTablet ? 8 : 4,
    },
    emptyText: {
      color: colors.textDisabled,
      fontSize: isTablet ? 15 : 14,
      fontWeight: '500',
      paddingVertical: isTablet ? 8 : 4,
    },
  });
